plugin:
    type: plugin
    name: Pinterest
    description: |
        Pinterest integration for your shop
    fa_icon: pinterest
    fields:
        asynchronous:
            type: checkbox
            label: elcodi_plugin.pinterest.asynchronous
