author: Elcodi Team
description: |
    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    Mauris ac nibh a eros auctor lobortis. Etiam pellentesque diam nibh, id sagittis nisi finibus ac.
    Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
    In accumsan leo in neque dictum, quis mattis ligula consectetur
year: 2015
url: http://url-pinterest-plugin.com
name: Pinterest
fa_icon: pinterest
configuration_route: admin_pinterest_configuration
version: ~0.4
visible: true
